@startuml component

[gateway] as gw  #LightGray
[books] as books #LightGray
[catalog] as catalog #LightGray
[user-service] as user #LightGray
[auth-service] as auth #LightGray
[review] as review #LightGray
[subscription] as sub #LightGray
[email-notify] as e_notify #LightGray

database "Postgres" as pg_books #LightCoral
boundary "Minio" as minio #LightCoral
database "Postgres" as pg_catalog #LightCoral
database "Mongo" as mg_user #LightCoral
boundary "Keycloak" as kk #LightCoral
database "Mongo" as mg_review #LightCoral
queue "Kafka" as kafka #LightCoral

gw --> books
gw --> catalog
gw --> user
gw --> auth
gw --> review
gw --> sub

catalog -left--> books
catalog --> pg_catalog
catalog --> kafka
books --> pg_books
books --> minio
books --> kafka
user --> mg_user
user --> kk
user --> kafka
auth --> kk
review --> mg_review

sub --> kafka
kafka --> sub
kafka --> e_notify


@enduml