@startuml component

[gateway] as gw  #LightGray
[user-service] as user #LightGray
[catalog] as catalog #LightGray
[books] as books #LightGray
[review] as review #LightGray
[email-notify] as e_notify #LightGray
[subscription] as sub #LightGray

database "Postgres" as pg_books #LightCoral
boundary "Minio" as minio #LightCoral
database "Postgres" as pg_catalog #LightCoral
database "Postgres" as pg_user #LightCoral
boundary "Keycloak" as kk #LightCoral
database "Mongo" as mg_review #LightCoral
database "Mongo" as mg_sub #LightCoral
database "Postgres" as pg_email #LightCoral
queue "Kafka" as kafka #LightCoral

gw -down--> catalog
gw -down--> books
gw -down--> user
gw -down--> review
gw -down--> sub


user -down-> kk
user -down--> pg_user
user -down--> kafka
catalog -down--> kafka
catalog -right-> books
catalog -down--> pg_catalog
books -down--> kafka
books -down--> pg_books
books -down--> minio
review -down--> mg_review

sub -up--> kafka
sub -right->mg_sub
kafka -down--> sub
kafka -down--> e_notify
e_notify -left--> pg_email


@enduml