server:
  port: 8080
  error:
    whitelabel:
      enabled: true
spring:
  application:
    name: "otus-user"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}
      maximum-pool-size: ${DATASOURCE_MAXIMUM_POOL_SIZE}
      connection-timeout: ${DATASOURCE_CONNECTION_TIMEOUT}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        show_sql: false
        format_sql: false
        generate_statistics: false
        cache:
          use_second_level_cache: false

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus, health, metrics'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

sleepMinTime: ${SLEEP_MIN_TIME}
sleepMaxTime: ${SLEEP_MAX_TIME}