{
 "title": "Otus Howework",
 "time": { "from": "2024-12-25T13:18:46.101Z", "to": "2024-12-25T13:31:23.749Z" },
 "templating": {
  "list": [
   {
    "name": "appPodInstance",
    "label": "User App Pod Instance",
    "query": {
     "query": "label_values({job=\"users-app\"},instance)"
    }
   },
   { "name": "Interval", "query": "30sec,1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Latency ingress controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Ingress controller error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(sum(rate(nginx_ingress_controller_requests{status=~\"5..\"}[1m]))/sum(rate(nginx_ingress_controller_requests[1m]))) * 100",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Latency by pod instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{instance=\"$appPodInstance\",uri!~\"/actuator/.*\"}[1m])) by (le, method, uri))",
     "legendFormat": "0.99 ({{method}} {{uri}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{instance=\"$appPodInstance\",uri!~\"/actuator/.*\"}[1m])) by (le, method, uri))",
     "legendFormat": "0.95 ({{method}} {{uri}})"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{instance=\"$appPodInstance\",uri!~\"/actuator/.*\"}[1m])) by (le, method, uri))",
     "legendFormat": "0.5 ({{method}} {{uri}})"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$appPodInstance\",uri!~\"/actuator/.*\"}[1m])) by (method, uri, status)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\", pod=\"$appPodInstance\"}[1m])) by (instance, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"cadvisor\", pod=\"$appPodInstance\"}) by (instance, pod)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_xact_commit[$Interval])))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum ((rate(pg_stat_database_xact_rollback[$Interval])))",
     "legendFormat": "rollback"
    }
   ]
  }
 ]
}