FROM openjdk:17-jdk-alpine
COPY target/hw-05-*.jar /app.jar
EXPOSE 8080

ENV DB_HOST=""
ENV DB_PORT=""
ENV DB_NAME=""
ENV DB_SCHEMA=""
ENV DB_USERNAME=""
ENV DB_PASSWORD=""
ENV DATASOURCE_MAXIMUM_POOL_SIZE=""
ENV DATASOURCE_CONNECTION_TIMEOUT=""

ENTRYPOINT ["java", "-jar", "/app.jar"]