apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "otus-users.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ .Release.Name }}-postgresql"
  DB_PORT: "{{ .Values.postgresql.service.port }}"
  DB_NAME: "{{ .Values.postgresql.auth.database }}"
  DB_SCHEMA: "{{ .Values.postgresql.schema }}"
  DB_USERNAME: "{{ .Values.postgresql.auth.username }}"