apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrations
  labels:
    {{- include "otus-users.labels" . | nindent 4 }}
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 {{ .Release.Name }}-postgresql {{ .Values.postgresql.service.port }}; do echo "Waiting for PostgreSQL..."; sleep 1; done' ]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: DB_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: DB_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: DB_NAME
            - name: DATABASE_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: DB_SCHEMA
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: DB_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: password
      restartPolicy: OnFailure