apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  labels:
    {{- include "otus-users.labels" . | nindent 4 }}
type: Opaque
data:
  password: dXNlclBhc3N3b3Jk
  postgres-password: cG9zdGdyZXM=