apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "otus-prometheus.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ .Release.Name }}-postgresql"
  DB_PORT: "{{ .Values.postgresql.service.port }}"
  DB_NAME: "{{ .Values.postgresql.auth.database }}"
  DB_SCHEMA: "{{ .Values.postgresql.schema }}"
  DB_USERNAME: "{{ .Values.postgresql.auth.username }}"
  DB_ADMIN_USERNAME: "postgres"
  DATASOURCE_MAXIMUM_POOL_SIZE: "20"
  DATASOURCE_CONNECTION_TIMEOUT: "1000"
  SLEEP_MIN_TIME: "0.1"
  SLEEP_MAX_TIME: "1.5"