apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "otus-prometheus.labels" . | nindent 4 }}
type: Opaque
data:
  password: dXNlclBhc3N3b3Jk
  postgres-password: cG9zdGdyZXM=