@startuml

actor "User" as user
participant "gateway" as gw
participant "user-service" as us
boundary "Keycloak" as kk

user -> gw: POST /api/v1/sign-in
gw -> us: /api/v1/sign-in
us -> kk: us by login/password
kk --> us
alt #lightgreen Credentials are valid
    us --> gw: jwt
    gw --> user: jwt
else #coral [Credentials] are valid
    us --> gw: HttpStatus 401
    gw --> user: HttpStatus 401
end

@enduml